replicaCount: 1

image:
  repository: ghcr.io/shanginn/generach.rf
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer: letsencrypt-prod
  hosts:
    - xn--80afga3bt4c.xn--p1ai
  tls:
    - secretName: generach-tls
      hosts:
        - xn--80afga3bt4c.xn--p1ai

serviceAccount:
  create: true
  name: "generach"
